/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VUE;
import CONTROLEUR_BD.FormeDAO;
import MODEL_BD.FORME;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TIGER FOX
 */
public class Menu extends javax.swing.JFrame {
    static boolean isplain=false; // paramètre qui renseigne si la forme est pleine ou non
    static Connection con;
    DefaultTableModel model;
    FORME shapeModified;
    FormeDAO FDAO=new FormeDAO();
    
    
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        //mettre les figures dans la table
        TableFigures();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxFactory1 = new com.github.misberner.graphvizawtshapes.factories.BoxFactory();
        jColorChooser1 = new javax.swing.JColorChooser();
        jMenuItem1 = new javax.swing.JMenuItem();
        flatDesktopIconUI1 = new com.formdev.flatlaf.ui.FlatDesktopIconUI();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRect = new javax.swing.JButton();
        LargRect = new javax.swing.JLabel();
        LongRect = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnElp = new javax.swing.JButton();
        RayonX = new javax.swing.JLabel();
        RayonY = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnTri = new javax.swing.JButton();
        CoteTri = new javax.swing.JLabel();
        AireRet = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PerimRect = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        AireEllip = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PerimEllip = new javax.swing.JLabel();
        PerimHexa = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        AireHexa = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnLos = new javax.swing.JButton();
        DiagoLos = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        AireLos = new javax.swing.JLabel();
        PerimLos = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnHex = new javax.swing.JButton();
        RayonHex = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cooXrect = new javax.swing.JLabel();
        CooYrect = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        AireTri = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        PerimTri = new javax.swing.JLabel();
        EDITLABEL = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ColorDraw = new javax.swing.JColorChooser();
        ValidColor = new javax.swing.JButton();
        PanelDraw = new javax.swing.JPanel();
        Xlabel = new javax.swing.JLabel();
        Ylabel = new javax.swing.JLabel();
        plain = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        FigureNameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        FigureNameSearchField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FigureTypeField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        SupprimerBtn = new javax.swing.JButton();
        ActuBtn = new javax.swing.JButton();
        VisualiserBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFormes = new javax.swing.JTable();
        jMenuBar3 = new javax.swing.JMenuBar();
        FileBtn = new javax.swing.JMenu();
        SaveAsPng = new javax.swing.JMenuItem();
        SaveFigure = new javax.swing.JMenuItem();
        UpdateBtn = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        themeCheck = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONCOURS CANAM");

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECTANGLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("LONGEUR:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("LARGEUR:");

        btnRect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRect.setText("RECTANGLE");
        btnRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectActionPerformed(evt);
            }
        });

        LargRect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LargRect.setForeground(new java.awt.Color(255, 102, 0));
        LargRect.setText("X.xx");

        LongRect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LongRect.setForeground(new java.awt.Color(255, 102, 0));
        LongRect.setText("X.xx");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LongRect, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LargRect, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRect)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LargRect, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LongRect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRect, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ELIPSE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("RAYON-X:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("RAYON-Y:");

        btnElp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnElp.setText("ELIPSE");
        btnElp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElpActionPerformed(evt);
            }
        });

        RayonX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RayonX.setForeground(new java.awt.Color(255, 102, 0));
        RayonX.setText("X.xx");

        RayonY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RayonY.setForeground(new java.awt.Color(255, 102, 0));
        RayonY.setText("X.xx");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RayonX, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RayonY, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnElp))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RayonX, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RayonY, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnElp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRIANGLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("COTE:");

        btnTri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTri.setText("TRIANGLE");
        btnTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriActionPerformed(evt);
            }
        });

        CoteTri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CoteTri.setForeground(new java.awt.Color(255, 102, 0));
        CoteTri.setText("X.xx");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CoteTri, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnTri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTri, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CoteTri, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        AireRet.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        AireRet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AireRet.setText("X.X");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("AIRE :");

        PerimRect.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PerimRect.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerimRect.setText("X.X");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PERIM :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("AIRE :");

        AireEllip.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        AireEllip.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AireEllip.setText("X.X");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("PERIM :");

        PerimEllip.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PerimEllip.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerimEllip.setText("X.X");

        PerimHexa.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PerimHexa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerimHexa.setText("X.X");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("AIRE :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("PERIM :");

        AireHexa.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        AireHexa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AireHexa.setText("X.X");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOSANGE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("DIAGO :");

        btnLos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLos.setText("LOSANGE");
        btnLos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLosActionPerformed(evt);
            }
        });

        DiagoLos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DiagoLos.setForeground(new java.awt.Color(255, 102, 0));
        DiagoLos.setText("X.xx");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnLos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(DiagoLos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiagoLos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("PERIM :");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("AIRE :");

        AireLos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        AireLos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AireLos.setText("X.X");

        PerimLos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PerimLos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerimLos.setText("X.X");

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HEXAGONE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("RAYON:");

        btnHex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHex.setText("HEXAGONE");
        btnHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexActionPerformed(evt);
            }
        });

        RayonHex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RayonHex.setForeground(new java.awt.Color(255, 102, 0));
        RayonHex.setText("X.xx");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(RayonHex, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnHex)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RayonHex, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(btnHex, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ORIGINE:");

        cooXrect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cooXrect.setForeground(new java.awt.Color(255, 102, 0));
        cooXrect.setText("X.xx");

        CooYrect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CooYrect.setForeground(new java.awt.Color(255, 102, 0));
        CooYrect.setText("X.xx");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("AIRE :");

        AireTri.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        AireTri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AireTri.setText("X.X");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("PERIM :");

        PerimTri.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        PerimTri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PerimTri.setText("X.X");

        EDITLABEL.setBackground(new java.awt.Color(0, 0, 51));
        EDITLABEL.setForeground(new java.awt.Color(60, 63, 65));
        EDITLABEL.setText("EDITION");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cooXrect, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CooYrect, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PerimLos, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(AireLos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PerimRect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AireRet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(EDITLABEL)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PerimEllip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AireEllip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PerimHexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AireHexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PerimTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AireTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EDITLABEL)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AireRet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerimRect, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cooXrect, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CooYrect, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AireEllip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerimEllip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AireHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerimHexa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AireLos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerimLos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AireTri, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PerimTri, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ColorDraw.setAutoscrolls(true);
        ColorDraw.setColor(new java.awt.Color(51, 51, 255));
        ColorDraw.setDragEnabled(true);
        ColorDraw.setName(""); // NOI18N
        ColorDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorDrawMouseClicked(evt);
            }
        });

        ValidColor.setBackground(new java.awt.Color(56, 118, 227));
        ValidColor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ValidColor.setForeground(new java.awt.Color(255, 255, 255));
        ValidColor.setText("Appliquer Couleur");
        ValidColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidColorActionPerformed(evt);
            }
        });

        PanelDraw.setBackground(new java.awt.Color(255, 255, 255));
        PanelDraw.setToolTipText("X.xx");
        PanelDraw.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        DrawZone Dz=new DrawZone();
        PanelDraw.add(Dz);
        PanelDraw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelDrawMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelDrawMouseMoved(evt);
            }
        });
        PanelDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDrawMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelDrawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PanelDrawMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout PanelDrawLayout = new javax.swing.GroupLayout(PanelDraw);
        PanelDraw.setLayout(PanelDrawLayout);
        PanelDrawLayout.setHorizontalGroup(
            PanelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelDrawLayout.setVerticalGroup(
            PanelDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        Xlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Xlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Xlabel.setText("X");

        Ylabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ylabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ylabel.setText("Y");

        plain.setSelected(true);
        plain.setText("FIGURE PLEINE");
        plain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("NOM-FIGURE:");

        FigureNameField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        FigureNameField.setForeground(new java.awt.Color(255, 255, 0));
        FigureNameField.setText("fugure Canam");
        FigureNameField.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ValidColor)
                        .addGap(191, 191, 191)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FigureNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plain)
                        .addGap(144, 144, 144))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ColorDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ylabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Xlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(PanelDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Xlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ColorDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ValidColor)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FigureNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(plain))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ZONE DE TRAVAIL", jPanel1);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RECHERCHE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        FigureNameSearchField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FigureNameSearchField.setForeground(new java.awt.Color(255, 255, 0));
        FigureNameSearchField.setText("X");
        FigureNameSearchField.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("NOM-FIGURE:");

        FigureTypeField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FigureTypeField.setForeground(new java.awt.Color(255, 255, 0));
        FigureTypeField.setText("X");
        FigureTypeField.setToolTipText("");
        FigureTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FigureTypeFieldActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("TYPE:");

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("RECHERCHER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FigureNameSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(FigureTypeField)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FigureNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FigureTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        EditBtn.setBackground(new java.awt.Color(102, 102, 255));
        EditBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        EditBtn.setIcon(new javax.swing.ImageIcon("MODIFER.png"));
        EditBtn.setText("EDITER");
        EditBtn.setToolTipText("Selectionez un Travailet cliquez ici pour le modifier dans la base de Données");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        SupprimerBtn.setBackground(new java.awt.Color(204, 0, 0));
        SupprimerBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        SupprimerBtn.setIcon(new javax.swing.ImageIcon("DELETE.png"));
        SupprimerBtn.setForeground(new java.awt.Color(255, 255, 255));
        SupprimerBtn.setText("SUPPRIMER");
        SupprimerBtn.setToolTipText("Selectionez un Travailet cliquez ici pour le Supprimer dans la base de Données");
        SupprimerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprimerBtnActionPerformed(evt);
            }
        });

        ActuBtn.setBackground(new java.awt.Color(0, 255, 0));
        ActuBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ActuBtn.setIcon(new javax.swing.ImageIcon("ACTU.png"));
        ActuBtn.setForeground(new java.awt.Color(255, 255, 255));
        ActuBtn.setText("ACTUALISER");
        ActuBtn.setToolTipText("Cliquez ici pour actualiser la table des figures");
        ActuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActuBtnActionPerformed(evt);
            }
        });

        VisualiserBtn.setBackground(new java.awt.Color(102, 102, 255));
        VisualiserBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        VisualiserBtn.setText("VISUALISER");
        VisualiserBtn.setToolTipText("Selectionez un Travailet cliquez ici pour le visualiser");
        VisualiserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualiserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VisualiserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprimerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ActuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SupprimerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisualiserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        TableFormes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TableFormes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOM", "TYPE", "COULEUR", "x1", "y1", "x2", "y2", "angle", "r", "is_plain", "DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableFormes);
        if (TableFormes.getColumnModel().getColumnCount() > 0) {
            TableFormes.getColumnModel().getColumn(0).setPreferredWidth(10);
            TableFormes.getColumnModel().getColumn(4).setPreferredWidth(60);
            TableFormes.getColumnModel().getColumn(4).setMaxWidth(60);
            TableFormes.getColumnModel().getColumn(5).setPreferredWidth(60);
            TableFormes.getColumnModel().getColumn(5).setMaxWidth(60);
            TableFormes.getColumnModel().getColumn(6).setPreferredWidth(60);
            TableFormes.getColumnModel().getColumn(6).setMaxWidth(60);
            TableFormes.getColumnModel().getColumn(7).setPreferredWidth(60);
            TableFormes.getColumnModel().getColumn(7).setMaxWidth(60);
            TableFormes.getColumnModel().getColumn(8).setPreferredWidth(60);
            TableFormes.getColumnModel().getColumn(8).setMaxWidth(60);
            TableFormes.getColumnModel().getColumn(9).setPreferredWidth(60);
            TableFormes.getColumnModel().getColumn(9).setMaxWidth(60);
            TableFormes.getColumnModel().getColumn(10).setMaxWidth(80);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MES FORMES", jPanel2);

        jMenuBar3.setBorder(null);
        jMenuBar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FileBtn.setText("FICHIER");
        FileBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SaveAsPng.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveAsPng.setText("EXPORTER L'IMAGE");
        SaveAsPng.setToolTipText("Exporter sous forme d'image dans un format choisi par vous ");
        SaveAsPng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsPngActionPerformed(evt);
            }
        });
        FileBtn.add(SaveAsPng);

        SaveFigure.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SaveFigure.setText("ENREGISTRER LE TRAVAIL");
        SaveFigure.setToolTipText("Enregistrez votre travail en Base de Données");
        SaveFigure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFigureActionPerformed(evt);
            }
        });
        FileBtn.add(SaveFigure);

        UpdateBtn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        UpdateBtn.setText("METTRE A JOUR LE TRAVAIL");
        UpdateBtn.setToolTipText("POUR METTRE A JOUR UN DESSIN DEJA FAIT QUE VOUS VOULEZ EDITER");
        UpdateBtn.setEnabled(false);
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        FileBtn.add(UpdateBtn);

        jMenuBar3.add(FileBtn);

        jMenu6.setText("PREFERENCES");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        themeCheck.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        themeCheck.setSelected(true);
        themeCheck.setText("DARK MODE");
        themeCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeCheckActionPerformed(evt);
            }
        });
        jMenu6.add(themeCheck);

        jMenuBar3.add(jMenu6);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectActionPerformed
        // TODO add your handling code here:
        DrawZone.forme.type="Rectangle";
        JOptionPane.showMessageDialog(null, "FORME :"+DrawZone.forme.type);
    }//GEN-LAST:event_btnRectActionPerformed

    private void btnElpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElpActionPerformed
        // TODO add your handling code here:
        DrawZone.forme.type="Ellipse";
        JOptionPane.showMessageDialog(null, "FORME :"+DrawZone.forme.type);
        
    }//GEN-LAST:event_btnElpActionPerformed

    private void btnTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriActionPerformed
        // TODO add your handling code here:
       DrawZone.forme.type="Triangle";
        JOptionPane.showMessageDialog(null, "FORME :"+DrawZone.forme.type);
    }//GEN-LAST:event_btnTriActionPerformed

    private void btnLosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLosActionPerformed
        // TODO add your handling code here:
       DrawZone.forme.type="Rhombus";
        JOptionPane.showMessageDialog(null, "FORME :"+DrawZone.forme.type);
    }//GEN-LAST:event_btnLosActionPerformed

    private void themeCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeCheckActionPerformed
        // TODO add your handling code here:
        
        // Cette fonction change le thème de couleur de l'interface graphique en fonction de l'état du composant themeCheck
        // Si themeCheck est sélectionné, la fonction applique le thème FlatMacDarkLaf, qui est un thème sombre
        // Sinon, la fonction applique le thème FlatMacLightLaf, qui est un thème clair
        // La fonction utilise la bibliothèque FlatLaf pour gérer les thèmes de couleur
        // La fonction utilise également la classe FlatAnimatedLafChange pour créer une animation de transition entre les thèmes
        // La fonction utilise la méthode invokeLater de la classe EventQueue pour exécuter le changement de thème dans le thread de l'interface graphique
        
        if (themeCheck.isSelected()) {
            EventQueue.invokeLater(new Runnable(){
            
            @Override
            public void run(){
                FlatAnimatedLafChange.showSnapshot();
                FlatMacDarkLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
                
            }
            
        });
            
        } else {
            
            EventQueue.invokeLater(new Runnable(){
            
            @Override
            public void run(){
               FlatAnimatedLafChange.showSnapshot();
                FlatMacLightLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
                
            }
            
        });
        }
        
        
       
    }//GEN-LAST:event_themeCheckActionPerformed

    private void PanelDrawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDrawMouseReleased
        // TODO add your handling code here:
      PanelDraw.setToolTipText("Y: "+Integer.toString(evt.getY())+" X: "+Integer.toString(evt.getX())); //je met ce tooltip pour indiquer à l'utilisateur les coordonées de l'écran

    }//GEN-LAST:event_PanelDrawMouseReleased

    private void PanelDrawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDrawMousePressed
        // TODO add your handling code here:
       
       // Récupérer les coordonnées du premier point
        
       
       
    }//GEN-LAST:event_PanelDrawMousePressed

    private void ValidColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidColorActionPerformed
        // TODO add your handling code here:
        // Pour valider la couleur choisie
        DrawZone.forme.color=ColorDraw.getColor();
        JOptionPane.showMessageDialog(null, "COULEUR : "+DrawZone.forme.color.toString()+"\nveuilliez deplacer la souri sur la zone de dessin pour Appliquer");
    }//GEN-LAST:event_ValidColorActionPerformed

    private void PanelDrawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDrawMouseDragged
        // TODO add your handling code here:
        AireRet.setText(Integer.toString(evt.getY()));
    }//GEN-LAST:event_PanelDrawMouseDragged

    private void PanelDrawMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDrawMouseMoved
       
    }//GEN-LAST:event_PanelDrawMouseMoved

    private void SaveAsPngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsPngActionPerformed
         // Cette fonction permet de sauvegarder l'image générée dans le panel de dessin sous format image (png)
        // La fonction utilise la classe JFileChooser pour afficher une boîte de dialogue qui permet à l'utilisateur de choisir le nom et l'emplacement du fichier image
        // La fonction utilise la classe ImageFilter pour filtrer les fichiers qui ne sont pas des images
        // La fonction utilise la classe BufferedImage pour créer une image à partir du contenu du panel de dessin
        // La fonction utilise la classe Graphics pour dessiner la forme sur l'image
        // La fonction utilise la classe ImageIO pour écrire l'image dans le fichier choisi
        // La fonction gère les exceptions de type IOException qui peuvent survenir lors de la création ou de l'écriture du fichier image
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("ENTREZ LE NOM DE VOTRE FICHIER IMAGE");
        fileChooser.setFileFilter(new ImageFilter());
        if (fileChooser.showSaveDialog(PanelDraw) == JFileChooser.APPROVE_OPTION) {
          File file = fileChooser.getSelectedFile();
            try {
                //creation d'un bjet buffered image a partir du contenu du Panel de dessin
                BufferedImage image= (BufferedImage)PanelDraw.createImage(PanelDraw.getWidth(),PanelDraw.getHeight());
                Graphics g=image.getGraphics();
                PanelDraw.paint(g); // ce code est là pour que l'image générée ne soit pas vide , on redessine la figure sur e panelDraw
                ImageIO.write(image, "png", file);
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SaveAsPngActionPerformed

    private void plainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainActionPerformed
        // La fonction qui gere le clique sur la checkbox pour dire si la figure est pleine ou pas 
        
        isplain=!isplain;
        JOptionPane.showMessageDialog(null, "figure pleine!\nveuilliez deplacer la souri sur la zone de dessin pour voir");
    }//GEN-LAST:event_plainActionPerformed

    private void ColorDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorDrawMouseClicked
        //Fonction pour attrbuer la couleur selectionée l'orsque l'utilisateur clique sur le selecteur de couleur
        DrawZone.forme.color=ColorDraw.getColor();
    }//GEN-LAST:event_ColorDrawMouseClicked

    private void btnHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexActionPerformed
        // TODO add your handling code here:
        DrawZone.forme.type="Hexagon";
        JOptionPane.showMessageDialog(null, "FORME :"+DrawZone.forme.type);
    }//GEN-LAST:event_btnHexActionPerformed

    private void PanelDrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDrawMouseExited
        // TODO add your handling code here:
    PanelDraw.setToolTipText("Y: ? X: ?"); //je met ce tooltip pour indiquer à l'utilisateur les coordonées de l'écran

    }//GEN-LAST:event_PanelDrawMouseExited

    private void VisualiserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualiserBtnActionPerformed
        // TODO add your handling code here:
        //je recupere les données de la forme selectionée pour construire la visualisation
        VisuZone.angle=(float)TableFormes.getValueAt(TableFormes.getSelectedRow(), 8);
        VisuZone.r=(float)TableFormes.getValueAt(TableFormes.getSelectedRow(), 9);
        VisuZone.x1=(int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 4);
        VisuZone.x2=(int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 6);
        VisuZone.y1=(int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 5);
        VisuZone.y2=(int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 7);
        String strCOlor=(String)TableFormes.getValueAt(TableFormes.getSelectedRow(), 3);
        VisuZone.color=new Color( Integer.parseInt(strCOlor.split(" ")[0]) , Integer.parseInt(strCOlor.split(" ")[1]), Integer.parseInt(strCOlor.split(" ")[2]));
        VisuZone.shape=(String)TableFormes.getValueAt(TableFormes.getSelectedRow(), 2);
        VisuZone.is_plain=(boolean)TableFormes.getValueAt(TableFormes.getSelectedRow(), 10);
        
        new VisualisationScreen().setVisible(true);
    }//GEN-LAST:event_VisualiserBtnActionPerformed

    private void FigureTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FigureTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FigureTypeFieldActionPerformed

    private void ActuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActuBtnActionPerformed
        // TODO add your handling code here:
        ViderTableFigures();
        ViderTableFigures();
        TableFigures();
    }//GEN-LAST:event_ActuBtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ViderTableFigures();
        ViderTableFigures();
        TablesearchFigures(FigureNameSearchField.getText(), FigureTypeField.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void SaveFigureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFigureActionPerformed
        // TODO add your handling code here:
        DrawZone.forme.setName(FigureNameField.getText());
        DrawZone.forme.setIs_plain(!isplain); // g'enregistre la forme en base de Données
        FDAO.insert(DrawZone.forme);
        UpdateBtn.setEnabled(false); // on desactive le bouton de mise a jour
        FigureNameField.setEnabled(true);
        EDITLABEL.setForeground(new Color(60, 63, 65));
        ViderTableFigures();
        ViderTableFigures();
        TableFigures();
    }//GEN-LAST:event_SaveFigureActionPerformed

    private void SupprimerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprimerBtnActionPerformed
        // TODO add your handling code here:
        // methode pour supprimer de la bd en prenant la premiere colone de la table comme ID
        int selectedRow;
        int dialogResult=JOptionPane.showConfirmDialog(null, "voulez vous vraiment supprimer ce travail ?","Confirmation",JOptionPane.YES_OPTION);
        int selectedFigureID;
        try {
            System.out.println(TableFormes.getValueAt(TableFormes.getSelectedRow(), 0).getClass().getSimpleName());
            selectedFigureID =(int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 0);
            if(dialogResult==JOptionPane.YES_OPTION){
                selectedRow=TableFormes.getSelectedRow();
                model.removeRow(selectedRow);
                FDAO.delete(selectedFigureID);
                ViderTableFigures();
                ViderTableFigures();
                TableFigures();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "OUPS!! une erreur s'est produite");
        }
    }//GEN-LAST:event_SupprimerBtnActionPerformed

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        String strCOlor="";
        try {
        FigureNameField.setText((String)TableFormes.getValueAt(TableFormes.getSelectedRow(), 1));
         strCOlor=(String)TableFormes.getValueAt(TableFormes.getSelectedRow(), 3);
        DrawZone.forme.setID((int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 0));
        System.out.println(DrawZone.forme.getID());
        isplain=!(boolean)TableFormes.getValueAt(TableFormes.getSelectedRow(), 10);
        JOptionPane.showMessageDialog(null, "Mode Edition de la forme "+DrawZone.forme.getID());
        EDITLABEL.setForeground(Color.ORANGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "veuillez selectioner une ligne avant");
        }
        
        
        plain.setSelected(!isplain); // on doit mettre a jour le champ qui indique si la figure est pleine 
        DrawZone.forme=new FORME(
                (int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 0),
                (int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 4), 
                (int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 5),
                (int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 6),
                (int)TableFormes.getValueAt(TableFormes.getSelectedRow(), 7),
                (float)TableFormes.getValueAt(TableFormes.getSelectedRow(), 9),
                (String)TableFormes.getValueAt(TableFormes.getSelectedRow(), 1),
                (boolean)TableFormes.getValueAt(TableFormes.getSelectedRow(), 10),
                (float)TableFormes.getValueAt(TableFormes.getSelectedRow(), 8),
                new Color( Integer.parseInt(strCOlor.split(" ")[0]) , Integer.parseInt(strCOlor.split(" ")[1]), Integer.parseInt(strCOlor.split(" ")[2])),
                (String)TableFormes.getValueAt(TableFormes.getSelectedRow(), 2));
        
       try {
           shapeModified =  DrawZone.forme.clone(); ////ici il faut mettre un constructeur de copie
        } catch (CloneNotSupportedException ex) {
            ex.printStackTrace();
        } 
        
       new DrawZone(true).repaint();
       System.out.println("lident est "+shapeModified.getID());
       UpdateBtn.setEnabled(true); // on active la mise à jour
       FigureNameField.setEnabled(false);
    }//GEN-LAST:event_EditBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
        DrawZone.forme.setID(shapeModified.getID());
        DrawZone.forme.setIs_plain(plain.isSelected());
        FDAO.update(DrawZone.forme); // on met a jour la forme dans la BD
         FigureNameField.setEnabled(true);
         UpdateBtn.setEnabled(false);
         EDITLABEL.setForeground(new Color(60, 63, 65));
         ViderTableFigures();
         ViderTableFigures();
         TableFigures();
                
        
    }//GEN-LAST:event_UpdateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup(); //fonction pour appliquer le theme de l'interface

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActuBtn;
    public static javax.swing.JLabel AireEllip;
    public static javax.swing.JLabel AireHexa;
    public static javax.swing.JLabel AireLos;
    public static javax.swing.JLabel AireRet;
    public static javax.swing.JLabel AireTri;
    private javax.swing.JColorChooser ColorDraw;
    public static javax.swing.JLabel CooYrect;
    public static javax.swing.JLabel CoteTri;
    public static javax.swing.JLabel DiagoLos;
    private javax.swing.JLabel EDITLABEL;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTextField FigureNameField;
    private javax.swing.JTextField FigureNameSearchField;
    private javax.swing.JTextField FigureTypeField;
    private javax.swing.JMenu FileBtn;
    public static javax.swing.JLabel LargRect;
    public static javax.swing.JLabel LongRect;
    private static javax.swing.JPanel PanelDraw;
    public static javax.swing.JLabel PerimEllip;
    public static javax.swing.JLabel PerimHexa;
    public static javax.swing.JLabel PerimLos;
    public static javax.swing.JLabel PerimRect;
    public static javax.swing.JLabel PerimTri;
    public static javax.swing.JLabel RayonHex;
    public static javax.swing.JLabel RayonX;
    public static javax.swing.JLabel RayonY;
    private javax.swing.JMenuItem SaveAsPng;
    private javax.swing.JMenuItem SaveFigure;
    private javax.swing.JButton SupprimerBtn;
    private javax.swing.JTable TableFormes;
    private javax.swing.JMenuItem UpdateBtn;
    private javax.swing.JButton ValidColor;
    private javax.swing.JButton VisualiserBtn;
    public static javax.swing.JLabel Xlabel;
    public static javax.swing.JLabel Ylabel;
    private com.github.misberner.graphvizawtshapes.factories.BoxFactory boxFactory1;
    private javax.swing.JButton btnElp;
    private javax.swing.JButton btnHex;
    private javax.swing.JButton btnLos;
    private javax.swing.JButton btnRect;
    private javax.swing.JButton btnTri;
    public static javax.swing.JLabel cooXrect;
    private com.formdev.flatlaf.ui.FlatDesktopIconUI flatDesktopIconUI1;
    private javax.swing.JButton jButton7;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox plain;
    private javax.swing.JCheckBoxMenuItem themeCheck;
    // End of variables declaration//GEN-END:variables

    /************************************************************************************/
    /************************************************************************************/

// Cette fonction affiche la table des figures dans le modèle de la JTable TableFormes
// La fonction utilise la méthode Select de la classe FormeDAO pour récupérer la liste des formes stockées dans la base de données
// La fonction parcourt la liste des formes et ajoute chaque forme comme une ligne du modèle de la JTable
// La fonction utilise un tableau d'objets pour stocker les informations de chaque forme, tels que l'ID, le nom, le type, la couleur, les coordonnées, l'angle, le rayon, le remplissage et la date
private void TableFigures() {
        
        List<FORME> lis= FDAO.Select();
        model = (DefaultTableModel)TableFormes.getModel();
        Object[] ob =new Object[12];
        for (int i = 0; i < lis.size(); i++) {
            ob[0] = lis.get(i).getID();
            ob[1]=lis.get(i).getName();
            ob[2]=lis.get(i).getType();
            ob[3]=lis.get(i).getColor();
            ob[4]=lis.get(i).getX1();
            ob[5]=lis.get(i).getY1();
            ob[6]=lis.get(i).getX2();
            ob[7]=lis.get(i).getY2();
            ob[8]=lis.get(i).getAngle();
            ob[9]=lis.get(i).getR();
            ob[10]=lis.get(i).getIs_plain();
            ob[11]=lis.get(i).getDate();
            
            model.addRow(ob);
        }

    } //methode qui génère la table des figures
    
    
// Cette fonction affiche la table des figures recherchées dans le modèle de la JTable TableFormes
// La fonction prend en paramètre le nom et le type de la forme recherchée
// La fonction utilise la méthode Search de la classe FormeDAO pour récupérer la liste des formes qui correspondent aux critères de recherche
// La fonction parcourt la liste des formes et ajoute chaque forme comme une ligne du modèle de la JTable
// La fonction utilise un tableau d'objets pour stocker les informations de chaque forme, tels que l'ID, le nom, le type, la couleur, les coordonnées, l'angle, le rayon, le remplissage et la date
private void TablesearchFigures(String name , String type) {
        List<FORME> lis= FDAO.Search(type, name);
//            for (int i = 0; i < model.getRowCount(); i++) {
//            model.removeRow(i);}
        model = (DefaultTableModel)TableFormes.getModel();
        Object[] ob =new Object[12];
        for (int i = 0; i < lis.size(); i++) {
            ob[0] = lis.get(i).getID();
            ob[1]=lis.get(i).getName();
            ob[2]=lis.get(i).getType();
            ob[3]=lis.get(i).getColor();
            ob[4]=lis.get(i).getX1();
            ob[5]=lis.get(i).getY1();
            ob[6]=lis.get(i).getX2();
            ob[7]=lis.get(i).getY2();
            ob[8]=lis.get(i).getAngle();
            ob[9]=lis.get(i).getR();
            ob[10]=lis.get(i).getIs_plain();
            ob[11]=lis.get(i).getDate();
            model.addRow(ob);
        }
    }
    
    // Cette fonction vide le modèle de la JTable TableFormes
    // La fonction parcourt les lignes du modèle et les supprime une par une
private void ViderTableFigures() {
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(i);
            i--;
              
        }
           
    }

    
    /****************************************************************************/
    /*****************************************************************************/




}

// la classe pour le choix du fichier image à Exporter

class ImageFilter extends FileFilter {

  @Override
  public boolean accept(File f) {
    if (f.isDirectory()) {
      return true;
    }
    String name = f.getName().toLowerCase();
    return name.endsWith(".jpg") || name.endsWith(".png");
  }

  @Override
  public String getDescription() {
    return "Images (*.jpg, *.png)";
  }
}
/************************************************************************************/
    
